### ISSUE TITLE
数据显示出现问题

### ISSUE THREAD

**Issue by dive2Pro** [DMQ/mvvm#5]
demo中的例子:

```html
<div id="mvvm-app">
    <input type="text" v-model="someStr">
    <input type="text" v-model="child.someStr">
    <!-- <p v-class="className" class="abc">
        {{someStr}}
        <span v-text="child.someStr"></span>
    </p> -->
    <p>{{getHelloWord}}</p>
    <p v-html="child.htmlStr"></p>
    <button v-on:click="clickBtn">change model</button>
    <br>
      {{getHelloWord}} {{getHelloWord}} <!-- 如果这样设置会出现错误, -->
    <br>

</div>
```

错误如下:

```
watcher.js:50 Uncaught TypeError: Cannot read property 'call' of undefined
    at Watcher.get (http://localhost:63342/mvvm/js/watcher.js:50:32)
    at Watcher (http://localhost:63342/mvvm/js/watcher.js:13:23)
    at Object.bind (http://localhost:63342/mvvm/js/compile.js:128:9)
    at Object.text (http://localhost:63342/mvvm/js/compile.js:96:14)
    at Compile.compileText (http://localhost:63342/mvvm/js/compile.js:73:21)
    at http://localhost:63342/mvvm/js/compile.js:41:20
    at Array.forEach (native)
    at Compile.compileElement (http://localhost:63342/mvvm/js/compile.js:33:35)
    at Compile.init (http://localhost:63342/mvvm/js/compile.js:26:14)
    at Compile (http://localhost:63342/mvvm/js/compile.js:7:14)

```
 
而且如果在 Element 是这样设置的
`<div>Hello ,{{someStr}} </div>`, 你的做法会将{{model}}填充整个节点,只留下`<div>{{someStr}} </div>`

**Comment by DMQ** [comment]
@dive2Pro 是的，目前是存在这样的问题，因为这个mvvm只是做一个示例，指令解析这一块也是简单的处理，并没有考虑很多复杂情况哈，感谢你的提醒！
